apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-tc8r
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0008-tenant/tkrw-pr712-0075-0008-app/devfile-sample-tc8r@sha256:d364514117741416f93e60491f0e4e86a91b1b3aacfa7a38d2c2e6a405ddd58b
        name: my-nodejs
        resources: {}
status: {}
